import { createSlice } from "@reduxjs/toolkit"; // Import functions from Redux Toolkit

// Create a slice using createSlice function
const searchSlice = createSlice({
	name: "search", // Slice name
	initialState: {
		// Initial state of the slice
		history: [], // Array to store search history
		favorites: [], // Array to store favorite searches
	},
	reducers: {
		// Define reducer functions
		addSearch: (state, action) => {
			// Reducer function to add a search to history
			state.history.push(action.payload); // Add the search to the history array
		},
	},
});

// Export the action creator for addSearch
export const { addSearch } = searchSlice.actions;

// Export the reducer function generated by createSlice
export default searchSlice.reducer;
